// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxlxXqr6LdZCcrdWtRUtWOK6hG1m2lhy8',
    appId: '1:937546130022:web:5fb0cc18e401a9a70b03a7',
    messagingSenderId: '937546130022',
    projectId: 'helpa-b1891',
    authDomain: 'helpa-b1891.firebaseapp.com',
    storageBucket: 'helpa-b1891.firebasestorage.app',
    measurementId: 'G-HGP8JXY409',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUijYtDWFcMBuB0if7uzHC7Zdir9H8R6Q',
    appId: '1:937546130022:android:3fed9fc65f4e430a0b03a7',
    messagingSenderId: '937546130022',
    projectId: 'helpa-b1891',
    storageBucket: 'helpa-b1891.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuU3wD-I5TnnGGjTovhiBSY1BUr-8MJ20',
    appId: '1:937546130022:ios:6ef02f5673741a9b0b03a7',
    messagingSenderId: '937546130022',
    projectId: 'helpa-b1891',
    storageBucket: 'helpa-b1891.firebasestorage.app',
    iosClientId: '937546130022-io0r3sfuqnqdblba1d3k2tc9e3vidjh2.apps.googleusercontent.com',
    iosBundleId: 'com.example.helpa',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuU3wD-I5TnnGGjTovhiBSY1BUr-8MJ20',
    appId: '1:937546130022:ios:6ef02f5673741a9b0b03a7',
    messagingSenderId: '937546130022',
    projectId: 'helpa-b1891',
    storageBucket: 'helpa-b1891.firebasestorage.app',
    iosClientId: '937546130022-io0r3sfuqnqdblba1d3k2tc9e3vidjh2.apps.googleusercontent.com',
    iosBundleId: 'com.example.helpa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxlxXqr6LdZCcrdWtRUtWOK6hG1m2lhy8',
    appId: '1:937546130022:web:bc2011b7f8a6eb320b03a7',
    messagingSenderId: '937546130022',
    projectId: 'helpa-b1891',
    authDomain: 'helpa-b1891.firebaseapp.com',
    storageBucket: 'helpa-b1891.firebasestorage.app',
    measurementId: 'G-9V8FRN52CW',
  );
}
